CREATE TABLE PRODUCT(
    PRODUCT_ID NUMBER(5),
    PRODUCT_NAME VARCHAR2(30),
    PRODUCT_TYPE NUMBER(1),
    PRODUCT_PRICE NUMBER(5, 2),
    PRODUCT_TITLE VARCHAR2(800),
    PRODUCT_DESC VARCHAR2(800),
    PRODUCT_IMG VARCHAR2(400),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE COFFEEUSER(
    COFFEEUSER_ID NUMBER(5),
    COFFEEUSER_NAME VARCHAR2(30),
    COFFEEUSER_PASS VARCHAR2(30),
    COFFEEUSER_EMAIL VARCHAR2(30),
    CONSTRAINT PK_COFFEEUSER PRIMARY KEY (COFFEEUSER_ID),
    CONSTRAINT UQ_COFFEEUSER UNIQUE (COFFEEUSER_EMAIL)
);

CREATE TABLE SHOPPINGCART(
    SHOPPINGCART_ID NUMBER(5),
    COFFEEUSER_ID NUMBER(5),
    PRODUCT_ID NUMBER(5),
    QUANTITY NUMBER(2),
    CONSTRAINT PK_SHOPPINGCART PRIMARY KEY (SHOPPINGCART_ID),
    CONSTRAINT FK_COFFEEUSER FOREIGN KEY (COFFEEUSER_ID) REFERENCES COFFEEUSER(COFFEEUSER_ID),
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    CONSTRAINT UQ_SHOPPINGCART UNIQUE (COFFEEUSER_ID, PRODUCT_ID)
);

CREATE TABLE BILL (
    BILL_ID INT PRIMARY KEY,
    TOTAL DECIMAL(10, 2),
    PAYMENT_METHOD VARCHAR(50),
    BILL_NUMBER VARCHAR(50),
    BILL_DATE DATE,
    BILL_DESC VARCHAR(100)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    EMPLOYEE_EMAIL VARCHAR(100)
);

CREATE TABLE ADMIN_PANEL (
    ADMIN_PANEL_ID INT PRIMARY KEY,
    EMPLOYEE_ID INT,
    CREATE_PERMISSION INT,
    READ_PERMISSION INT,
    DELETE_PERMISSION INT,
    UPDATE_PERMISSION INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);