-- LA TABLA TYPE LA OMITIMOS YA QUE SOLO DEJAMOS CONSTANCIA EN
-- MODELO DE TABLAS, EL MODELO E/R Y EN EL DICCIONARIO DE DATOS


-- Creación de la tabla PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER(5),
    PRODUCT_NAME VARCHAR2(30),
    PRODUCT_TYPE NUMBER(1),
    PRODUCT_PRICE NUMBER(5, 2),
    PRODUCT_TITLE VARCHAR2(800),
    PRODUCT_DESC VARCHAR2(800),
    PRODUCT_IMG VARCHAR2(400),
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCT_ID)
);

-- Creación de la tabla COFFEE_USER
CREATE TABLE COFFEE_USER (
    COFFEE_USER_ID NUMBER(5),
    COFFEE_USER_NAME VARCHAR2(100),
    COFFEE_USER_PASS VARCHAR2(100),
    COFFEE_USER_EMAIL VARCHAR2(300),
    CONSTRAINT PK_COFFEE_USER PRIMARY KEY (COFFEE_USER_ID),
    CONSTRAINT UQ_COFFEE_USER UNIQUE (COFFEE_USER_EMAIL)
);

-- Creación de la tabla EMPLOYEE
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID NUMBER(5),
    EMPLOYEE_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    ADDRESS VARCHAR2(100),
    EMPLOYEE_EMAIL VARCHAR2(300),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID)
);

-- Creación de la tabla STORE
CREATE TABLE STORE (
    STORE_ID NUMBER(5),
    STORE_ADDRESS VARCHAR2(100),
    CONSTRAINT PK_STORE PRIMARY KEY (STORE_ID)
);

-- Creación de la tabla STOCK
CREATE TABLE STOCK (
    STORE_ID NUMBER(5),
    PRODUCT_ID NUMBER(5),
    STOCK_QUANTITY NUMBER(5),
    CONSTRAINT FK_STOCK_STORE FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID),
    CONSTRAINT FK_STOCK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
);

-- Creación de la tabla ORDER_USER
CREATE TABLE ORDER_USER (
    ORDER_NUMBER_ID NUMBER(5),
    COFFEE_USER_ID NUMBER(5),
    ORDER_STATUS VARCHAR2(50),
    TOTAL NUMBER(8, 2),
    DATE_ORDER DATE,
    CONSTRAINT PK_ORDER_USER PRIMARY KEY (ORDER_NUMBER_ID),
    CONSTRAINT FK_ORDER_USER_COFFEE_USER FOREIGN KEY (COFFEE_USER_ID) REFERENCES COFFEE_USER(COFFEE_USER_ID)
);

-- Creación de la tabla ORDER_DETAILS
CREATE TABLE ORDER_DETAILS (
    ORDER_NUMBER_ID NUMBER(5),
    PRODUCT_ID NUMBER(5),
    DATE_ADDED DATE,
    QUANTITY NUMBER(5),
    TOTAL NUMBER(8, 2),
    CONSTRAINT FK_ORDER_DETAILS_ORDER_USER FOREIGN KEY (ORDER_NUMBER_ID) REFERENCES ORDER_USER(ORDER_NUMBER_ID),
    CONSTRAINT FK_ORDER_DETAILS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- Creación de la tabla STORE_STAFF
CREATE TABLE STORE_STAFF (
    EMPLOYEE_ID NUMBER(5),
    STORE_ID NUMBER(5),
    SCHEDULE VARCHAR2(100),
    POSITION VARCHAR2(50),
    SALARY NUMBER(10, 2),
    CONSTRAINT FK_STORE_STAFF_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT FK_STORE_STAFF_STORE FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);