-- Eliminación de la tabla STORE_STAFF
ALTER TABLE STORE_STAFF DROP CONSTRAINT FK_STORE_STAFF_EMPLOYEE;

ALTER TABLE STORE_STAFF DROP CONSTRAINT FK_STORE_STAFF_STORE;

DROP TABLE STORE_STAFF;

-- Eliminación de la tabla ORDER_DETAILS
ALTER TABLE ORDER_DETAILS DROP CONSTRAINT FK_ORDER_DETAILS_COFFEE_USER;

ALTER TABLE ORDER_DETAILS DROP CONSTRAINT FK_ORDER_DETAILS_PRODUCT;

DROP TABLE ORDER_DETAILS;

-- Eliminación de la tabla ORDER_USER
ALTER TABLE ORDER_USER DROP CONSTRAINT FK_ORDER_USER_COFFEE_USER;

ALTER TABLE ORDER_USER DROP CONSTRAINT FK_ORDER_USER_PRODUCT;

DROP TABLE ORDER_USER;

-- Eliminación de la tabla STOCK
ALTER TABLE STOCK DROP CONSTRAINT FK_STOCK_STORE;

ALTER TABLE STOCK DROP CONSTRAINT FK_STOCK_PRODUCT;

DROP TABLE STOCK;

-- Eliminación de la tabla STORE
DROP TABLE STORE;

-- Eliminación de la tabla EMPLOYEE
DROP TABLE EMPLOYEE;

-- Eliminación de la tabla COFFEE_USER
DROP TABLE COFFEE_USER;

-- Eliminación de la tabla PRODUCT
DROP TABLE PRODUCT;