-- Eliminar restricciones de clave externa
ALTER TABLE STOCK DROP CONSTRAINT FK_STOCK_STORE;

ALTER TABLE STOCK DROP CONSTRAINT FK_STOCK_PRODUCT;

ALTER TABLE ORDER_DETAILS DROP CONSTRAINT FK_ORDER_DETAILS_ORDER_USER;

ALTER TABLE ORDER_DETAILS DROP CONSTRAINT FK_ORDER_DETAILS_PRODUCT;

ALTER TABLE ORDER_USER DROP CONSTRAINT FK_ORDER_USER_COFFEE_USER;

ALTER TABLE STORE_STAFF DROP CONSTRAINT FK_STORE_STAFF_EMPLOYEE;

ALTER TABLE STORE_STAFF DROP CONSTRAINT FK_STORE_STAFF_STORE;

-- Eliminar restricciones de clave primaria
ALTER TABLE ORDER_USER DROP CONSTRAINT PK_ORDER_USER;

ALTER TABLE STOCK DROP CONSTRAINT PK_STOCK;

ALTER TABLE PRODUCT DROP CONSTRAINT PK_PRODUCT;

ALTER TABLE COFFEE_USER DROP CONSTRAINT PK_COFFEE_USER;

ALTER TABLE EMPLOYEE DROP CONSTRAINT PK_EMPLOYEE;

ALTER TABLE STORE DROP CONSTRAINT PK_STORE;

-- Eliminar tablas
DROP TABLE ORDER_DETAILS;

DROP TABLE ORDER_USER;

DROP TABLE STORE_STAFF;

DROP TABLE STOCK;

DROP TABLE PRODUCT;

DROP TABLE COFFEE_USER;

DROP TABLE EMPLOYEE;

DROP TABLE STORE;