--PLAN DE CONTINGENCIA
--ELIMINACION DE TODAS LAS TABLAS EN CASO DE COLAPSO


-- Eliminar la tabla BILL y todas las restricciones
ALTER TABLE BILL DROP CONSTRAINT FK_BILL_EMPLOYEE;

DROP TABLE BILL;

-- Eliminar la tabla ADMIN_PANEL y todas las restricciones
ALTER TABLE ADMIN_PANEL DROP CONSTRAINT FK_ADMIN_PANEL_EMPLOYEE;

DROP TABLE ADMIN_PANEL;

-- Eliminar la tabla SHOPPINGCART y todas las restricciones
ALTER TABLE SHOPPINGCART DROP CONSTRAINT FK_SHOPPINGCART_COFFEEUSER;

ALTER TABLE SHOPPINGCART DROP CONSTRAINT FK_SHOPPINGCART_PRODUCT;

ALTER TABLE SHOPPINGCART DROP CONSTRAINT UQ_SHOPPINGCART;

DROP TABLE SHOPPINGCART;

-- Eliminar la tabla COFFEEUSER y todas las restricciones
ALTER TABLE COFFEEUSER DROP CONSTRAINT UQ_COFFEEUSER;

DROP TABLE COFFEEUSER;

-- Eliminar la tabla PRODUCT y todas las restricciones
ALTER TABLE PRODUCT DROP CONSTRAINT PK_PRODUCT;

DROP TABLE PRODUCT;

-- Eliminar la tabla EMPLOYEE y todas las restricciones
DROP TABLE EMPLOYEE;